# Site settings
title: John Garner - GARNER.IO
tag_text: John Garner - GARNER.IO
description: Iâ€™m a learner, designer, artist, and software engineer.
# baseurl: "/blog" # the subpath of your site, e.g. /blog
# url: "https://example.com" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
